lib{lyrahgames-xstd}: {hxx ixx txx}{** -version} hxx{version}
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
}

hxx{version}: in{version} $src_root/manifest
{
  dist = true
  clean = ($src_root != $out_root)
}

{hxx ixx txx}{*}:
{
  install = include/lyrahgames/xstd/
  install.subdirs = true
}
